# -*- coding: utf-8 -*

TCP_CONN_COUNT = 8
TCP_SERVER_ADDR = '127.0.0.1'
TCP_SERVER_PORT = 9999
TCP_RECV_BUFF_LEN = 1024
TCP_RPC_EVENT_TIMEOUT = 3  # 单位： s
TCP_RECONNECT_TIME = 5

REDIS_DB_ID = 1

AUTH_ACTION_REGISTER = 1
AUTH_ACTION_LOGIN = 2
AUTH_GET_USER_INFO = 3

AUTH_SESSION_TIMEOUT = 86400  # 24h

COMMENT_TABLE_COUNT = 5
GEN_ID_BGEIN_MS_TIME = 1649918750149

AUTH_USER_STATUS_OK = 0
AUTH_USER_STATUS_NOT_REGISTER = 1
AUTH_USER_STATUS_TIME_OUT = 2
AUTH_USER_STATUS_NOT_LOGIN = 3

ERR_OK = 0
ERR_USER_NOT_EXISTS = 1005
ERR_WROING_SESSION = 2000
ERR_SESSION_TIMEOUT = 2001
ERR_USER_NOT_LOGIN = 2002
ERR_USER_NOT_RESISTER = 2003
ERR_UNKNOWN_ERROR = 2004
ERR_DATA_NOT_EXISTS = 2005
ERR_INVALID_REQUEST = 2006
ERR_INVALID_PRODUCT = 2007

STATUS_TO_ERRCODE_DICT = {
    AUTH_USER_STATUS_OK: ERR_OK,
    AUTH_USER_STATUS_NOT_REGISTER: ERR_USER_NOT_RESISTER,
    AUTH_USER_STATUS_TIME_OUT: ERR_SESSION_TIMEOUT,
    AUTH_USER_STATUS_NOT_LOGIN: ERR_USER_NOT_LOGIN
}
