use minimarket_product_db;
drop table comment_resp;
drop table comment;
drop table product;
use minimarket_user_db;
drop table user0;
drop table user1;
drop table user2;
drop table user3;
drop table user4;
drop table user5;
drop table user6;
drop table user7;
drop table user8;
drop table user9;